[package]
name = "agents"
version = "0.1.0"
authors = ["Matt Porter <matt_porter@hotmail.co.uk>"]

[dependencies.sdl2]
version = "0.31"
default-features = false
features = ["ttf","image","gfx","mixer"]